enabled_fonts:
  - 'local_fonts://vagrounded'
  - 'local_fonts://petplan_icomoonico'
  - 'local_fonts://hand_of_sean'
  - 'local_fonts://avenirltstd_black'
  - 'local_fonts://avenir_medium'
  - 'local_fonts://avenirltstd_book'
  - 'local_fonts://avenirltstd_heavy'
load_all_enabled_fonts: 1
_core:
  default_config_hash: r8uAx4mTBwCkgDFbdKCmhjgbb91BQ4HbWSYRKrlowMY
